export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const STARTING_PRODUCT_DOWNLOAD = 'STARTING_PRODUCT_DOWNLOAD';
export const PRODUCT_DOWNLOAD_SUCCESS = 'PRODUCT_DOWNLOAD_SUCCESS';
export const PRODUCT_DOWNLOAD = 'PRODUCT_DOWNLOAD_ERROR';